#!/bin/bash
g++ ConsoleApplication13.cpp -o fields
./fields
echo "Fields done"
g++ ConsoleApplication15.cpp -o densities
./densities
echo "Densities done"
gnuplot -persist plot_densities.plt
gnuplot -persist plot_full_energi.plt
echo "Graphs done"

